(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }

  root.UiPreviewScenarios = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const DEFAULT_SCENARIO_ID = "ready-to-drive";
  const TRACKS_BASE = [
    { id: "track_001", name: "Ningbo Kart Center" },
    { id: "track_002", name: "Shanghai International Circuit" },
    { id: "track_003", name: "Zhuhai International Circuit" },
    { id: "track_004", name: "Tianma Circuit" },
    { id: "track_005", name: "Ningbo South Layout" },
    { id: "track_006", name: "Hangzhou Kart Track" },
  ];

  const SCENARIOS = [
    {
      id: "cold-boot",
      label: "Cold Boot",
      status: {
        gps_fix: false,
        satellites: 0,
        lat: 0,
        lon: 0,
        recording: false,
        current_lap: 0,
        best_lap_ms: 0,
        track: "No Track",
        track_id: "",
        track_source: "Waiting to select",
        track_locked_manual: false,
        recording_cta_state: "blocked_no_track",
        recording_cta_reason: "Select a track before recording.",
      },
      sessions: [],
      tracks: TRACKS_BASE.slice(0, 1),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "boot",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "splash",
        firmware_version: "v1.0.0",
        uptime_seconds: 3,
      },
    },
    {
      id: "gps-searching",
      label: "GPS Searching",
      status: {
        gps_fix: false,
        satellites: 4,
        lat: 0,
        lon: 0,
        recording: false,
        current_lap: 0,
        best_lap_ms: 0,
        track: "No Track",
        track_id: "",
        track_source: "Waiting to select",
        track_locked_manual: false,
        recording_cta_state: "blocked_no_track",
        recording_cta_reason: "Select a track before recording.",
      },
      sessions: [],
      tracks: TRACKS_BASE.slice(0, 1),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "boot",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "gps-searching",
        firmware_version: "v1.0.0",
        uptime_seconds: 14,
      },
    },
    {
      id: "ready-to-drive",
      label: "Ready To Drive",
      status: {
        gps_fix: true,
        satellites: 10,
        lat: 29.8243561,
        lon: 121.5584237,
        recording: false,
        current_lap: 1,
        best_lap_ms: 52380,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "ready",
        recording_cta_reason: "",
      },
      sessions: [],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      track_creation: {
        name: "",
        sectorsExpanded: false,
      },
      device: {
        screen: "driving",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 96,
        sd_free_gb: 13.8,
      },
    },
    {
      id: "track-creation-stabilizing",
      label: "Track Creation Stabilizing",
      status: {
        gps_fix: true,
        satellites: 4,
        lat: 29.8243561,
        lon: 121.5584237,
        recording: false,
        current_lap: 1,
        best_lap_ms: 52380,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "ready",
        recording_cta_reason: "",
      },
      sessions: [],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      track_creation: {
        name: "Ningbo Pit Exit",
        gps: {
          fix: true,
          satellites: 4,
          lat: 29.8243561,
          lon: 121.5584237,
          stability: "stabilizing",
        },
        sectorsExpanded: false,
        message: {
          kind: "",
          text: "Stand still for a few seconds before marking P1.",
        },
      },
      device: {
        screen: "driving",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 102,
        sd_free_gb: 13.7,
      },
    },
    {
      id: "no-gps-driving",
      label: "No GPS",
      status: {
        gps_fix: false,
        satellites: 0,
        lat: 0,
        lon: 0,
        recording: true,
        current_lap: 3,
        best_lap_ms: 52380,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_00.vbo"],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "driving",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 2,
        best_lap_number: 1,
        current_lap_time_ms: 24420,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 318,
        sd_free_gb: 13.5,
      },
    },
    {
      id: "manual-track-selected",
      label: "Manual Track Selected",
      status: {
        gps_fix: true,
        satellites: 9,
        lat: 29.8245201,
        lon: 121.5589322,
        recording: false,
        current_lap: 0,
        best_lap_ms: 0,
        track: "Shanghai International Circuit",
        track_id: "track_002",
        track_source: "Selected manually",
        track_locked_manual: true,
        recording_cta_state: "ready",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_08.vbo"],
      tracks: TRACKS_BASE.slice(0, 3),
      nearby_tracks: [
        { id: "track_003", name: "Zhuhai International Circuit", distance_m: 18 },
        { id: "track_001", name: "Ningbo Kart Center", distance_m: 96 },
      ],
      current_track_distance_m: 36,
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "status",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 632,
        sd_free_gb: 12.8,
      },
    },
    {
      id: "recording",
      label: "Recording",
      status: {
        gps_fix: true,
        satellites: 11,
        lat: 29.824462,
        lon: 121.5589322,
        recording: true,
        current_lap: 4,
        best_lap_ms: 51230,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_01.vbo"],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      track_creation: {
        name: "Ningbo Practice Loop",
        startFinish: {
          p1: { lat: 29.8243521, lon: 121.5585123 },
          p2: { lat: 29.8244421, lon: 121.5587048 },
          flipped: false,
        },
        sectorsExpanded: true,
        sectors: [
          {
            id: "sector_1",
            p1: { lat: 29.8246721, lon: 121.5589922 },
            p2: { lat: 29.8247041, lon: 121.5592028 },
            flipped: false,
          },
          {
            id: "sector_2",
            p1: { lat: 29.824812, lon: 121.5594321 },
            p2: null,
            flipped: false,
          },
        ],
        message: {
          kind: "error",
          text: "Complete or delete every sector split before creating the track.",
        },
      },
      device: {
        screen: "driving",
        delta_ms: -130,
        delta_valid: true,
        off_track: false,
        lap_count: 4,
        best_lap_number: 3,
        current_lap_time_ms: 18890,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 842,
        sd_free_gb: 13.4,
      },
    },
    {
      id: "recording-slow",
      label: "Recording Slow",
      status: {
        gps_fix: true,
        satellites: 11,
        lat: 29.8245871,
        lon: 121.5591046,
        recording: true,
        current_lap: 5,
        best_lap_ms: 51230,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_06.vbo"],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "driving",
        delta_ms: 240,
        delta_valid: true,
        off_track: false,
        lap_count: 5,
        best_lap_number: 3,
        current_lap_time_ms: 20110,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 901,
        sd_free_gb: 13.3,
      },
    },
    {
      id: "sector-focus",
      label: "Sector Focus",
      status: {
        gps_fix: true,
        satellites: 11,
        lat: 29.8246202,
        lon: 121.5592459,
        recording: true,
        current_lap: 6,
        best_lap_ms: 50890,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_07.vbo"],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "driving",
        delta_ms: -60,
        delta_valid: true,
        off_track: false,
        lap_count: 5,
        best_lap_number: 4,
        current_lap_time_ms: 33420,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 962,
        sd_free_gb: 13.2,
        sectors: [
          { label: "S1", delta_ms: -50, state: "completed" },
          { label: "S2", delta_ms: 120, state: "focus" },
          { label: "S3", state: "live" },
        ],
      },
    },
    {
      id: "best-lap-improved",
      label: "Best Lap Improved",
      status: {
        gps_fix: true,
        satellites: 12,
        lat: 29.8246911,
        lon: 121.559318,
        recording: true,
        current_lap: 7,
        best_lap_ms: 50120,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_02.vbo"],
      tracks: TRACKS_BASE.slice(0, 1),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      track_creation: {
        name: "Ningbo Sprint Layout",
        startFinish: {
          p1: { lat: 29.8245801, lon: 121.5590284 },
          p2: { lat: 29.8246489, lon: 121.5592411 },
          flipped: false,
        },
        sectorsExpanded: true,
        sectors: [
          {
            id: "sector_1",
            p1: { lat: 29.8248203, lon: 121.5595133 },
            p2: { lat: 29.8248592, lon: 121.5597048 },
            flipped: false,
          },
        ],
      },
      device: {
        screen: "driving",
        delta_ms: -280,
        delta_valid: true,
        off_track: false,
        lap_count: 7,
        best_lap_number: 7,
        current_lap_time_ms: 430,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 1114,
        sd_free_gb: 13.2,
      },
    },
    {
      id: "guided-track-review",
      label: "Guided Track Review",
      status: {
        gps_fix: true,
        satellites: 10,
        lat: 29.8245801,
        lon: 121.5590284,
        recording: false,
        current_lap: 0,
        best_lap_ms: 0,
        track: "No Track",
        track_id: "",
        track_source: "Waiting to select",
        track_locked_manual: false,
        recording_cta_state: "blocked_no_track",
        recording_cta_reason: "Select a track before recording.",
      },
      sessions: [],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      track_creation: {
        name: "Ningbo Sprint Layout",
        stage: "review",
        gps: {
          fix: true,
          satellites: 10,
          lat: 29.8245801,
          lon: 121.5590284,
          stability: "stable",
        },
        startFinish: {
          p1: { lat: 29.8245801, lon: 121.5590284 },
          p2: { lat: 29.8246489, lon: 121.5592411 },
          flipped: false,
        },
        sectorsExpanded: true,
        sectors: [
          {
            id: "sector_1",
            p1: { lat: 29.8248203, lon: 121.5595133 },
            p2: { lat: 29.8248592, lon: 121.5597048 },
            flipped: false,
          },
        ],
        message: {
          kind: "",
          text: "Review the geometry before creating the track.",
        },
      },
      device: {
        screen: "status",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 514,
        sd_free_gb: 12.6,
      },
    },
    {
      id: "off-track",
      label: "Off Track",
      status: {
        gps_fix: true,
        satellites: 9,
        lat: 29.8261501,
        lon: 121.5610401,
        recording: true,
        current_lap: 5,
        best_lap_ms: 51540,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "recording",
        recording_cta_reason: "",
      },
      sessions: ["session_20260408_03.vbo"],
      tracks: TRACKS_BASE.slice(0, 1),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "driving",
        delta_ms: 0,
        delta_valid: false,
        off_track: true,
        lap_count: 5,
        best_lap_number: 3,
        current_lap_time_ms: 32180,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 934,
        sd_free_gb: 13.1,
      },
    },
    {
      id: "session-review",
      label: "Session Review",
      status: {
        gps_fix: true,
        satellites: 10,
        lat: 29.824301,
        lon: 121.5582014,
        recording: false,
        current_lap: 0,
        best_lap_ms: 50890,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "ready",
        recording_cta_reason: "",
      },
      sessions: [
        {
          filename: "20260408_Ningbo Kart Center_140530_001.vbo",
          date: "2026-04-08 14:05",
          track: "Ningbo Kart Center",
          best_lap_ms: 50890,
        },
        {
          filename: "20260407_Ningbo Kart Center_174210_001.vbo",
          date: "2026-04-07 17:42",
          track: "Ningbo Kart Center",
          best_lap_ms: 51310,
        },
      ],
      tracks: TRACKS_BASE.slice(0, 2),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "lap-list",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 9,
        best_lap_number: 6,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 1262,
        sd_free_gb: 12.9,
        laps: [
          { lap_number: 1, lap_time_ms: 52840, status: "timed" },
          { lap_number: 2, lap_time_ms: 52220, status: "timed" },
          { lap_number: 3, lap_time_ms: 51670, status: "timed" },
          { lap_number: 4, lap_time_ms: 51310, status: "timed" },
          { lap_number: 5, lap_time_ms: 51060, status: "timed" },
          { lap_number: 6, lap_time_ms: 50890, status: "timed" },
          { lap_number: 7, lap_time_ms: 51140, status: "timed" },
          { lap_number: 8, lap_time_ms: 51480, status: "timed" },
          { lap_number: 9, lap_time_ms: 51630, status: "timed" },
        ],
      },
    },
    {
      id: "heavy-track-library",
      label: "Heavy Track Library",
      status: {
        gps_fix: true,
        satellites: 11,
        lat: 29.824301,
        lon: 121.5582014,
        recording: false,
        current_lap: 0,
        best_lap_ms: 0,
        track: "Ningbo Kart Center",
        track_id: "track_001",
        track_source: "Auto-detected",
        track_locked_manual: false,
        recording_cta_state: "ready",
        recording_cta_reason: "",
      },
      sessions: [
        "session_20260408_05.vbo",
        "session_20260407_03.vbo",
        "session_20260405_01.vbo",
        "session_20260404_02.vbo",
        "session_20260402_01.vbo",
        "session_20260329_01.vbo",
      ],
      tracks: TRACKS_BASE.slice(0),
      settings: { wifi_ssid: "GPS-LapTimer", wifi_pass: "12345678", brightness: 200 },
      device: {
        screen: "status",
        delta_ms: 0,
        delta_valid: false,
        off_track: false,
        lap_count: 0,
        best_lap_number: -1,
        current_lap_time_ms: 0,
        boot_state: "ready",
        firmware_version: "v1.0.0",
        uptime_seconds: 412,
        sd_free_gb: 12.7,
      },
    },
  ];

  function getScenarioById(id) {
    const found = SCENARIOS.find(function (scenario) {
      return scenario.id === id;
    });

    if (found) {
      return found;
    }

    return (
      SCENARIOS.find(function (scenario) {
        return scenario.id === DEFAULT_SCENARIO_ID;
      }) || SCENARIOS[0]
    );
  }

  return {
    SCENARIOS: SCENARIOS,
    DEFAULT_SCENARIO_ID: DEFAULT_SCENARIO_ID,
    getScenarioById: getScenarioById,
  };
});
