#include "web_ui_internal.h"

static String build_web_ui_style_section();

String build_web_ui_head_section() {
    return "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
           "<title>GPS Lap Timer</title>"
           + build_web_ui_style_section() +
           "</head>";
}

static String build_web_ui_style_section() {
    return "<style>"
           "*{box-sizing:border-box;margin:0;padding:0}"
           "body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#eee;"
             "padding:16px;max-width:600px;margin:auto}"
           ".app-shell{display:grid;gap:12px;padding-bottom:calc(88px + env(safe-area-inset-bottom))}"
           "h1{text-align:center;color:#0ff;margin-bottom:16px;font-size:1.4em}"
           ".tab-section{display:none}"
           ".tab-section.active{display:block}"
           ".card{background:#16213e;border-radius:8px;padding:12px;margin-bottom:12px}"
           ".card h2{font-size:1em;color:#0af;margin-bottom:8px}"
           ".bottom-tabs{position:fixed;left:50%;transform:translateX(-50%);bottom:0;"
             "width:min(100%,600px);display:grid;grid-template-columns:repeat(3,minmax(0,1fr));"
             "gap:8px;padding:8px 12px calc(8px + env(safe-area-inset-bottom));"
             "background:rgba(10,18,35,0.96);border-top:1px solid #223;"
             "box-shadow:0 -10px 25px rgba(0,0,0,0.28);z-index:20}"
           ".tab-btn{margin:0;min-height:44px;padding:10px 8px;background:#10233a;color:#9eb3ca;"
             "border:1px solid #2a3c52;border-radius:12px;font-size:0.92em;font-weight:bold}"
           ".tab-btn:hover{background:#17304d}"
           ".tab-btn--active{background:#0af;color:#000;border-color:#7dd3fc}"
           ".tab-btn--active:hover{background:#0af}"
           ".row{display:flex;justify-content:space-between;padding:4px 0}"
           ".label{color:#888}.val{font-weight:bold}"
           ".ok{color:#0f0}.warn{color:#f80}.err{color:#f44}"
           "a{color:#0af;text-decoration:none}"
           "a:hover{text-decoration:underline}"
           "ul{list-style:none;padding:0}"
           "li{padding:4px 0;border-bottom:1px solid #223}"
           "input,select{background:#0d1b2a;color:#eee;border:1px solid #334;"
             "border-radius:4px;padding:6px 8px;width:100%;margin:4px 0}"
           "button{background:#0af;color:#000;border:none;border-radius:4px;"
             "padding:8px 16px;cursor:pointer;font-weight:bold;margin-top:8px}"
           "button:hover{background:#08d}"
           "button:disabled{background:#334;color:#889;cursor:not-allowed}"
           "button:disabled:hover{background:#334}"
           ".gps-bar{background:#0f1f32;border:1px solid #2a3c52;border-left:4px solid #f44;"
             "border-radius:8px;padding:10px;margin:8px 0}"
           ".gps-bar.ok{border-left-color:#0f0}"
           ".gps-bar.warn{border-left-color:#fa0}"
           ".gps-bar.err{border-left-color:#f44}"
           ".mark-row{display:flex;flex-direction:column;gap:6px;margin:8px 0}"
           ".mark-btn{width:100%;min-height:44px;padding:10px 12px;font-size:0.95em;"
             "margin-top:0}"
           ".mark-btn.marked{background:#12391f;color:#7ff5a1;border:1px solid #2faa5a}"
           ".mark-btn.cancel-btn{background:#45556f;color:#eef4ff}"
           ".coord{font-family:monospace;font-size:12px;color:#8ec5ff;"
             "word-break:break-word;padding:2px 0}"
           ".heading-bar{display:flex;align-items:center;justify-content:space-between;"
             "gap:8px;background:#0f1f32;border:1px solid #2a3c52;border-radius:8px;"
             "padding:8px;margin:8px 0}"
           ".heading-value{font-weight:bold;color:#d9ebff}"
           ".inline-btn{width:auto;min-height:0;padding:6px 10px;margin-top:0}"
           ".sector-card{border:1px solid #2a3c52;border-radius:8px;padding:8px;"
             "margin:8px 0;background:#0f1f32}"
           ".sector-head{display:flex;justify-content:space-between;align-items:center;"
             "gap:8px}"
           ".collapse-toggle{width:100%;text-align:left;background:#1b2f4c;color:#bcdfff;"
             "border:1px solid #355175;padding:10px 12px;margin-top:8px}"
           ".helper-text{color:#9eb3ca;font-size:12px;line-height:1.4;margin:4px 0}"
           ".current-track-panel{background:#0f1f32;border:1px solid #2a3c52;"
             "border-radius:8px;padding:10px;margin:10px 0}"
           ".current-track-head{align-items:center}"
           ".current-track-name{font-size:1.05em;font-weight:bold;color:#e8f3ff;"
             "margin-top:4px}"
           ".track-chip{display:inline-flex;align-items:center;justify-content:center;"
             "border:1px solid #355175;border-radius:999px;padding:2px 8px;font-size:11px;"
             "font-weight:bold;background:#17304d;color:#bcdfff}"
           ".track-chip.current{background:#12391f;border-color:#2faa5a;color:#7ff5a1}"
           ".track-row-name{display:flex;align-items:center;gap:8px;flex-wrap:wrap}"
           ".track-actions{display:flex;align-items:center;gap:4px}"
           ".track-meta{margin-top:6px}"
           ".recording-reason{min-height:1.4em}"
           ".nearby-track-list{display:grid;gap:8px}"
           ".nearby-track-row{display:flex;justify-content:space-between;align-items:center;"
             "gap:8px;border:1px solid #2a3c52;border-radius:8px;padding:8px;"
             "background:#12263d}"
           ".nearby-track-info{display:grid;gap:2px}"
           ".nearby-track-name{font-weight:bold;color:#e8f3ff}"
           ".nearby-track-distance{color:#9eb3ca;font-size:12px}"
           ".creation-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));"
             "gap:8px;margin:8px 0 12px}"
           ".creation-step{border:1px solid #2a3c52;border-radius:999px;padding:8px 10px;"
             "text-align:center;font-size:12px;color:#9eb3ca;background:#10233a}"
           ".creation-step.done{border-color:#2faa5a;color:#7ff5a1;background:#12391f}"
           ".creation-step.active{border-color:#60a5fa;color:#dbeafe;background:#17304d}"
           ".creation-stage{margin-bottom:12px}"
           ".review-panel svg{width:100%;height:auto;display:block}"
           ".review-metrics{display:grid;gap:6px;margin-top:10px}"
           ".review-badge{display:inline-flex;align-items:center;justify-content:center;"
             "width:max-content;max-width:100%;padding:4px 10px;border-radius:999px;"
             "font-size:12px;font-weight:bold;border:1px solid #355175}"
           ".review-badge.high{background:#12391f;border-color:#2faa5a;color:#7ff5a1}"
           ".review-badge.medium{background:#3a2d12;border-color:#f59e0b;color:#fde68a}"
           ".review-badge.low{background:#3b1720;border-color:#ef4444;color:#fecaca}"
           ".review-copy{margin-top:8px}"
           ".sessions-list{display:grid;gap:8px}"
           ".session-card{border:1px solid #2a3c52;border-radius:8px;padding:10px;"
             "background:#0f1f32;display:grid;gap:6px}"
           ".session-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));"
             "gap:8px;font-size:12px;color:#9eb3ca}"
           ".session-meta>div{min-width:0;overflow-wrap:anywhere;word-break:break-word}"
           ".session-meta strong{display:block;color:#dbeafe;font-size:11px;margin-bottom:2px}"
           ".session-actions{display:flex;justify-content:flex-end;min-width:0}"
           ".session-actions a{display:block;max-width:100%;overflow-wrap:anywhere;"
             "word-break:break-word;text-align:right}"
           ".advanced-toggle{width:100%;text-align:left;background:#0f1f32;color:#dbeafe;"
             "border:1px solid #2a3c52;padding:10px 12px;margin-top:0}"
           ".advanced-panel{margin-top:10px}"
           ".primary-btn:disabled{background:#334;color:#889;cursor:not-allowed}"
           ".track-msg-ok{color:#7ff5a1}"
           ".track-msg-err{color:#ff8f8f}"
           "#msg{text-align:center;color:#0f0;padding:8px;display:none}"
           "@media (orientation: landscape) and (max-height: 500px){"
             ".app-shell{padding-bottom:0;padding-top:12px}"
             ".bottom-tabs{position:sticky;left:auto;right:auto;bottom:auto;top:0;transform:none;"
               "width:auto;padding:6px 0;background:transparent;border-top:0;box-shadow:none}"
           "}"
           "@media (min-width:720px){"
             "body{max-width:840px}"
             ".app-shell{padding-bottom:0}"
             ".bottom-tabs{position:sticky;left:auto;right:auto;bottom:auto;top:0;transform:none;"
               "width:auto;padding:0 0 12px;background:transparent;border-top:0;box-shadow:none}"
           "}"
           "</style>";
}

String build_web_ui_body_section() {
    return "<body>"
           "<div id=\"app-shell\" class=\"app-shell\">"
           "<h1>GPS Lap Timer</h1>"

           "<div id=\"section-status\" class=\"tab-section active\">"
           "<div class=\"card\" id=\"status-card\">"
           "<h2>Status</h2>"
           "<div class=\"row\"><span class=\"label\">GPS Fix</span>"
             "<span class=\"val\" id=\"gps-fix\">--</span></div>"
           "<div class=\"row\"><span class=\"label\">Satellites</span>"
             "<span class=\"val\" id=\"sats\">--</span></div>"
           "<div class=\"row\"><span class=\"label\">Recording</span>"
             "<span class=\"val\" id=\"rec\">--</span></div>"
           "<div class=\"row\"><span class=\"label\">Current Lap</span>"
             "<span class=\"val\" id=\"lap\">--</span></div>"
           "<div class=\"row\"><span class=\"label\">Best Lap</span>"
             "<span class=\"val\" id=\"best\">--</span></div>"
           "<div class=\"row\"><span class=\"label\">Track</span>"
             "<span class=\"val\" id=\"track\">--</span></div>"
           "<button id=\"rec-btn\" onclick=\"toggleRecording()\" "
             "style=\"width:100%;padding:12px;font-size:1.1em;margin-top:8px\">"
             "Loading...</button>"
           "<div id=\"rec-cta-reason\" class=\"helper-text recording-reason\"></div>"
           "</div>"

           "<div class=\"card\">"
           "<button type=\"button\" id=\"advanced-toggle\" class=\"advanced-toggle\">Advanced</button>"
           "<div id=\"advanced-settings-panel\" class=\"advanced-panel\">"
           "<h2>Settings</h2>"
           "<div class=\"row\"><span class=\"label\">SSID</span>"
             "<input id=\"s-ssid\"></div>"
           "<div class=\"row\"><span class=\"label\">Password</span>"
             "<input id=\"s-pass\" type=\"password\"></div>"
           "<div class=\"row\"><span class=\"label\">Brightness</span>"
             "<input id=\"s-bright\" type=\"number\" min=\"0\" max=\"255\"></div>"
           "<button onclick=\"saveSettings()\">Save Settings</button>"
           "<div id=\"msg\">Saved!</div>"
           "<p style=\"color:#aaa;font-size:12px;margin-top:8px\">"
             "WiFi\xe5\x90\x8d\xe7\xa7\xb0\xe5\x92\x8c\xe5\xaf\x86\xe7\xa0\x81"
             "\xe4\xbf\xae\xe6\x94\xb9\xe5\x90\x8e\xe9\x9c\x80\xe9\x87\x8d\xe5\x90\xaf"
             "\xe7\x94\x9f\xe6\x95\x88\xe3\x80\x82"
             "\xe4\xba\xae\xe5\xba\xa6\xe7\xab\x8b\xe5\x8d\xb3\xe7\x94\x9f\xe6\x95\x88\xe3\x80\x82"
           "</p>"
           "</div>"
           "</div>"
           "</div>"

           "<div id=\"section-sessions\" class=\"tab-section\">"
           "<div class=\"card\">"
           "<h2>Sessions</h2>"
           "<div id=\"sessions\" class=\"sessions-list\"><div class=\"helper-text\">Loading...</div></div>"
           "</div>"
           "</div>"

           "<div id=\"section-tracks\" class=\"tab-section\">"
           "<div class=\"card\">"
           "<h2>Tracks</h2>"
           "<div class=\"current-track-panel\">"
           "<div class=\"row current-track-head\"><span class=\"label\">Current Track</span>"
             "<span id=\"current-track-lock\" class=\"track-chip\" style=\"display:none\"></span></div>"
           "<div id=\"current-track-name\" class=\"current-track-name\">Loading...</div>"
           "<div id=\"current-track-source\" class=\"helper-text track-meta\">--</div>"
           "<div id=\"current-track-distance\" class=\"helper-text track-meta\"></div>"
           "</div>"
           "<div class=\"current-track-panel\">"
           "<div id=\"nearby-tracks\" class=\"nearby-track-list\">"
             "<div class=\"helper-text\">Nearby tracks unavailable.</div>"
           "</div>"
           "</div>"
           "<ul id=\"tracks\"><li>Loading...</li></ul>"
           "<h2 style=\"margin-top:12px\">Track Creation</h2>"
           "<div id=\"creation-steps\" class=\"creation-steps\">"
           "<div id=\"creation-step-name\" class=\"creation-step\">1. Name</div>"
           "<div id=\"creation-step-start-finish\" class=\"creation-step\">2. Start/Finish</div>"
           "<div id=\"creation-step-review\" class=\"creation-step\">3. Review</div>"
           "</div>"
           "<div id=\"creation-stage-name\" class=\"creation-stage\">"
           "<p class=\"helper-text\">Name</p>"
           "<input id=\"track-name\" placeholder=\"Track name\">"
           "</div>"
           "<div id=\"creation-stage-start-finish\" class=\"creation-stage\">"
           "<div id=\"creation-guidance\" class=\"helper-text\"></div>"
           "<div id=\"gps-bar\" class=\"gps-bar err\">"
           "<div class=\"helper-text\">GPS status unavailable</div>"
           "</div>"
           "<div id=\"sf-section\">"
           "<p class=\"helper-text\">Start/Finish</p>"
           "<div class=\"mark-row\">"
           "<button type=\"button\" id=\"sf-p1-btn\" class=\"mark-btn\">Mark P1</button>"
           "<div id=\"sf-p1-coord\" class=\"coord\">Not set</div>"
           "</div>"
           "<div class=\"mark-row\">"
           "<button type=\"button\" id=\"sf-p2-btn\" class=\"mark-btn\" disabled>Mark P2</button>"
           "<div id=\"sf-p2-coord\" class=\"coord\">Not set</div>"
           "</div>"
           "<div id=\"sf-heading\" class=\"heading-bar\">"
           "<span id=\"sf-heading-text\" class=\"heading-value\">Heading pending</span>"
           "<button type=\"button\" id=\"sf-flip\" class=\"mark-btn inline-btn\" disabled>Flip</button>"
           "</div>"
           "</div>"
           "<button type=\"button\" id=\"sector-toggle\" class=\"collapse-toggle\">"
             "Sector Splits (optional)</button>"
           "<div id=\"sector-list\"></div>"
           "<button type=\"button\" id=\"add-sector-btn\" class=\"mark-btn\">+ Add Sector</button>"
           "<button type=\"button\" id=\"sample-cancel-btn\" class=\"mark-btn cancel-btn\" style=\"display:none\">"
             "Cancel Sample</button>"
           "</div>"
           "<div id=\"creation-stage-review\" class=\"creation-stage\">"
           "<div id=\"geometry-review\" class=\"current-track-panel review-panel\"></div>"
           "<div id=\"review-copy\" class=\"helper-text review-copy\"></div>"
           "<button type=\"button\" id=\"repeatability-btn\" class=\"mark-btn\" style=\"display:none\">"
             "Repeatability Check</button>"
           "<div id=\"repeatability-summary\" class=\"helper-text\"></div>"
           "<button type=\"button\" id=\"create-track-btn\" class=\"primary-btn\" disabled>"
             "Create Track</button>"
           "<div id=\"track-create-msg\" class=\"helper-text\"></div>"
           "</div>"
           "</div>"
           "</div>"

           "<nav id=\"bottom-tabs\" class=\"bottom-tabs\">"
           "<button type=\"button\" id=\"tab-status\" class=\"tab-btn tab-btn--active\" data-active=\"true\">Status</button>"
           "<button type=\"button\" id=\"tab-sessions\" class=\"tab-btn\" data-active=\"false\">Sessions</button>"
           "<button type=\"button\" id=\"tab-tracks\" class=\"tab-btn\" data-active=\"false\">Tracks</button>"
           "</nav>"
           "</div>"
           "</body>";
}
